apiVersion: v1
kind: Service
metadata:
  name: factorim-postgres-nodeport
spec:
  selector:
    app: factorim-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
