version: '3.7'

services:
  factorim-api:
    container_name: factorim-api
    build:
      context: .
      args:
        DB_PORT: ${DB_PORT}
        DEBUG_PORT: ${DEBUG_PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - DB_HOST=factorim-postgres
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@factorim-postgres:${DB_PORT}/${DB_DATABASE}?schema=${DB_SCHEMA}&sslmode=prefer
      - REDIS_URL=redis://:JustChangeMe@factorim-redis:6379
      - RABBITMQ_URL=amqp://factorim:JustChangeMe@factorim-rabbitmq:5672
    restart: unless-stopped
    networks:
      - factorim-network

networks:
  factorim-network:
    external: true
