name: Composer CD - Publish Docker Image

on:
  pull_request:
    branches: [release]
    paths:
      - "packages/composer/**"

jobs:
  publish-docker-image:
    name: "CD - Push Docker image to registry"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./packages/composer

      - name: Check if Docker image exists
        id: check-image
        run: |
          current_version="${{ steps.package-version.outputs.current-version }}"
          image_name="ghcr.io/factorim/factorim-composer-demo:$current_version"
          manifest=$(docker manifest inspect "$image_name" 2>&1) || true
          if [[ $manifest == *"manifest unknown"* ]]; then
            echo "Docker image $image_name does not exists. ✅ New version correctly set: $current_version."
            echo "image_exists=false" >> $GITHUB_OUTPUT
          else
            echo "Docker image $image_name already exists. Please bump the version in package.json and try again."
            echo "image_exists=true" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Build and Push Docker image
        if: steps.check-image.outputs.image_exists == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ./packages/composer
          file: ./packages/composer/Dockerfile
          push: true
          tags: |
            ghcr.io/factorim/factorim-composer-demo:${{ steps.package-version.outputs.current-version}}
            ghcr.io/factorim/factorim-composer-demo:latest
